on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: get comment
        run: |
          export BODY=curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.API_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/OWNER/REPO/issues/comments/1530469478 | jq .body | sed 's/[ ] https:\/\/github.com\/N0X0V\/upstream-repo\/pull\/2 /[x] https:\/\/github.com\/N0X0V\/upstream-repo\/pull\/2/' | xargs echo
      - name: update comment
        run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.API_TOKEN}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/N0X0V/downstream-repo/issues/comments/1530469478 -d '{"body":'$(echo $BODY)'}'