on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: update comment
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/N0X0V/downstream-repo/issues/comments/1530469478 \
          -d '{"body":"The upstream PR has been merged"}'
